<!--
  Licensed to the Apache Software Foundation (ASF) under one or more
  contributor license agreements.  See the NOTICE file distributed with
  this work for additional information regarding copyright ownership.
  The ASF licenses this file to You under the Apache License, Version 2.0
  (the "License"); you may not use this file except in compliance with
  the License.  You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
-->
<project basedir="." default="jar" name="cassandra-stress"
    xmlns:resolver="antlib:org.apache.maven.resolver.ant">

    <fail message="You need to use Ant of version at least 1.10 to continue.">
        <condition>
            <not>
                <antversion atleast="1.10" />
            </not>
        </condition>
    </fail>

    <property environment="env" />
    <property file="build.properties" />
    <property file="build.properties.default" />
    <property name="debuglevel" value="source,lines,vars" />

    <property name="base.version" value="3.12.0" />
    <property name="base.javaDriverVersion" value="3.11.5.18" />
    <property name="base.java4DriverVersion" value="4.19.2.1" />
    <property name="base.java4NativeProtocolVersion" value="1.5.2.2" />
    <property name="lib.override.com.scylladb.scylla-driver-core" value="" />

    <property name="basedir" value="." />
    <property name="build.src" value="${basedir}/src" />
    <property name="build.src.java" value="${basedir}/src/java" />
    <property name="build.src.resources" value="${basedir}/src/resources" />
    <property name="build.lib" value="${basedir}/lib" />
    <property name="build.dir" value="${basedir}/build" />
    <property name="build.dir.lib" value="${basedir}/build/lib" />
    <property name="build.test.dir" value="${build.dir}/test" />
    <property name="build.classes" value="${build.dir}/classes" />
    <property name="build.classes.main" value="${build.classes}/main" />
    <property name="test.dir" value="${basedir}/test" />
    <property name="test.resources" value="${test.dir}/resources" />
    <property name="test.lib" value="${build.dir}/test/lib" />
    <property name="test.classes" value="${build.dir}/test/classes" />
    <property name="test.name" value="*Test" />
    <property name="test.unit.src" value="${test.dir}/unit" />
    <property name="test.timeout" value="240000" />
    <property name="dist.dir" value="${build.dir}/dist" />
    <property name="tmp.dir" value="${java.io.tmpdir}" />

    <property name="jarjar.version" value="1.7.2" />
    <available file="${build.dir}/jarjar-${jarjar.version}.jar" property="jarjar.exists" />

    <property name="release.version" value="21" />

    <condition property="version" value="${base.version}">
        <isset property="release" />
    </condition>
    <property name="version" value="${base.version}-SNAPSHOT" />
    <property name="final.name" value="${ant.project.name}" />

    <property name="local.repository" value="${user.home}/.m2/repository" />

    <condition property="is.source.artifact">
        <available file="${build.src.java}" type="dir" />
    </condition>

    <condition property="scylla-driver-core.override.done">
        <available file="${scylla-driver-core.override.done.flag.path}" />
    </condition>

    <condition property="scylla-driver-core.override.want">
        <and>
            <not>
                <equals arg1="${lib.override.com.scylladb.scylla-driver-core}" arg2="" />
            </not>
            <available file="${lib.override.com.scylladb.scylla-driver-core}" />
        </and>
    </condition>

    <path id="cassandra-stress.classpath">
        <pathelement location="${build.classes.main}" />
        <fileset dir="${build.dir.lib}">
            <include name="**/*.jar" />
        </fileset>
    </path>
    <path id="cassandra-stress.classpath.test">
        <fileset dir="${build.dir.lib}">
            <include name="**/*.jar" />
            <exclude name="**/*-sources.jar" />
        </fileset>
        <fileset dir="${test.lib}/jars">
            <include name="**/*.jar" />
        </fileset>
    </path>

    <property name="resolver-ant-tasks.version" value="1.3.0" />
    <property name="resolver-ant-tasks.local"
        value="${local.repository}/org/apache/maven/resolver/maven-resolver-ant-tasks/${resolver-ant-tasks.version}/maven-resolver-ant-tasks-${resolver-ant-tasks.version}.jar" />
    <property name="resolver-ant-tasks.url"
        value="https://repo1.maven.org/maven2/org/apache/maven/resolver/maven-resolver-ant-tasks" />

    <condition property="resolver-ant-tasks.jar.exists">
        <available file="${resolver-ant-tasks.local}" />
    </condition>

    <path id="resolver-ant-tasks.classpath" path="${resolver-ant-tasks.local}" />

    <target name="_resolver_download" unless="resolver-ant-tasks.jar.exists"
        description="Fetch Resolver ANT Tasks from Maven Central Repository">
        <echo>Downloading Resolver ANT Tasks...</echo>
        <mkdir
            dir="${local.repository}/org/apache/maven/resolver/maven-resolver-ant-tasks/${resolver-ant-tasks.version}" />
        <get
            src="${resolver-ant-tasks.url}/${resolver-ant-tasks.version}/maven-resolver-ant-tasks-${resolver-ant-tasks.version}-uber.jar"
            dest="${resolver-ant-tasks.local}" usetimestamp="true" quiet="true" />
    </target>

    <target name="resolver-init" depends="init,_resolver_download,scylla-driver-core.override"
        unless="resolver-ant-tasks.initialized"
        description="Initialize Resolver ANT Tasks and declare the dependencies">
        <typedef uri="antlib:org.apache.maven.resolver.ant"
            resource="org/apache/maven/resolver/ant/antlib.xml"
            classpathref="resolver-ant-tasks.classpath" />
        <resolver:remoterepos id="all">
            <remoterepo id="resolver-central" url="${artifact.remoteRepository.central}" />
            <remoterepo id="resolver-apache" url="${artifact.remoteRepository.apache}" />
        </resolver:remoterepos>

        <resolver:dependencies id="runtime-deps">
            <dependency groupId="com.scylladb" artifactId="scylla-driver-core"
                version="${base.javaDriverVersion}" classifier="shaded">
                <exclusion groupId="io.netty" artifactId="netty-buffer" />
                <exclusion groupId="io.netty" artifactId="netty-codec" />
                <exclusion groupId="io.netty" artifactId="netty-handler" />
                <exclusion groupId="io.netty" artifactId="netty-transport" />
            </dependency>
            <dependency groupId="com.google.guava" artifactId="guava" version="33.3.1-jre">
                <exclusion groupId="com.google.code.findbugs" artifactId="jsr305" />
                <exclusion groupId="org.codehaus.mojo" artifactId="animal-sniffer-annotations" />
                <exclusion groupId="com.google.guava" artifactId="listenablefuture" />
                <exclusion groupId="org.checkerframework" artifactId="checker-qual" />
                <exclusion groupId="com.google.errorprone" artifactId="error_prone_annotations" />
            </dependency>
            <dependency groupId="org.apache.commons" artifactId="commons-math3" version="3.2" />
            <dependency groupId="org.apache.commons" artifactId="commons-lang3" version="3.1" />
            <dependency groupId="commons-cli" artifactId="commons-cli" version="1.1" />
            <dependency groupId="org.yaml" artifactId="snakeyaml" version="2.0" />
            <dependency groupId="com.googlecode.json-simple" artifactId="json-simple" version="1.1">
                <exclusion groupId="junit" artifactId="junit" />
            </dependency>
            <dependency groupId="org.jctools" artifactId="jctools-core" version="1.2.1" />
            <dependency groupId="io.netty" artifactId="netty-common" version="4.1.136.Final" />
            <dependency groupId="org.hdrhistogram" artifactId="HdrHistogram" version="2.2.2" />
            <dependency groupId="com.typesafe" artifactId="config" version="1.4.3" />
            <dependency groupId="org.slf4j" artifactId="slf4j-api" version="1.7.36" />
            <dependency groupId="ch.qos.logback" artifactId="logback-classic" version="1.2.13" />
            <dependency groupId="org.lz4" artifactId="lz4-java" version="1.8.1" />
            <dependency groupId="org.xerial.snappy" artifactId="snappy-java" version="1.1.10.4" />
        </resolver:dependencies>

        <resolver:dependencies id="test-deps">
            <dependency groupId="junit" artifactId="junit" version="4.12" scope="test">
                <exclusion groupId="org.hamcrest" artifactId="hamcrest-core" />
            </dependency>
            <dependency groupId="org.hamcrest" artifactId="hamcrest" version="2.2" scope="test" />
        </resolver:dependencies>

        <property name="resolver-ant-tasks.initialized" value="true" />
    </target>

    <target name="resolver-retrieve-build" depends="resolver-init,java-driver-core.shade">
        <resolver:resolve>
            <remoterepos refid="all" />
            <dependencies refid="runtime-deps" />
            <files dir="${build.dir.lib}/jars"
                layout="{artifactId}-{version}-{classifier}.{extension}"
                scopes="compile,runtime,!system" />
        </resolver:resolve>
        <resolver:resolve>
            <remoterepos refid="all" />
            <dependencies refid="test-deps" />
            <files dir="${test.lib}/jars" layout="{artifactId}-{version}-{classifier}.{extension}"
                scopes="test,!system" />
        </resolver:resolve>
    </target>

    <target name="init">
        <fail unless="is.source.artifact"
            message="Not a source artifact, stopping here." />
        <mkdir dir="${build.classes.main}" />
        <mkdir dir="${test.lib}" />
        <mkdir dir="${test.lib}/jars" />
        <mkdir dir="${test.classes}" />
        <mkdir dir="${build.dir.lib}" />
    </target>

    <target name="clean" description="Remove all locally created artifacts">
        <delete dir="${build.test.dir}" />
        <delete dir="${build.classes}" />
    </target>

    <target name="realclean" depends="clean"
        description="Remove the entire build directory and all downloaded artifacts">
        <delete dir="${build.lib}" />
        <delete dir="${build.dir}" />
    </target>

    <target name="jarjar.get" depends="init" unless="jarjar.exists">
        <echo>Downloading jarjar...</echo>
        <get src="https://repo1.maven.org/maven2/org/pantsbuild/jarjar/${jarjar.version}/jarjar-${jarjar.version}.jar"
             dest="${build.dir}/jarjar-${jarjar.version}.jar"
             skipexisting="true" />
        <get src="https://repo1.maven.org/maven2/org/ow2/asm/asm/9.1/asm-9.1.jar"
             dest="build/asm-9.1.jar"
             usetimestamp="true" />
        <get src="https://repo1.maven.org/maven2/org/ow2/asm/asm-commons/9.1/asm-commons-9.1.jar"
             dest="build/asm-commons-9.1.jar"
             usetimestamp="true" />
    </target>

    <target name="java-driver-core.get" depends="init">
        <echo>Downloading driver4 and dependencies...</echo>
        <mkdir dir="${build.dir}/shaded" />
        <mkdir dir="${build.dir}/lib/jars" />
        <get src="https://repo1.maven.org/maven2/com/scylladb/java-driver-core-shaded/${base.java4DriverVersion}/java-driver-core-shaded-${base.java4DriverVersion}.jar"
             dest="${build.dir}/shaded/java-driver-core-shaded-${base.java4DriverVersion}.jar"
             usetimestamp="true" />
        <get src="https://repo1.maven.org/maven2/com/scylladb/java-driver-guava-shaded/${base.java4DriverVersion}/java-driver-guava-shaded-${base.java4DriverVersion}.jar"
             dest="${build.dir}/shaded/java-driver-guava-shaded-${base.java4DriverVersion}.jar"
             usetimestamp="true" />
        <get src="https://repo1.maven.org/maven2/com/scylladb/native-protocol/${base.java4NativeProtocolVersion}/native-protocol-${base.java4NativeProtocolVersion}.jar"
             dest="${build.dir}/shaded/native-protocol-${base.java4NativeProtocolVersion}.jar"
             usetimestamp="true" />
    </target>

    <macrodef name="jarjar">
        <attribute name="input" />
        <attribute name="output" />
        <sequential>
            <java classname="org.pantsbuild.jarjar.Main" fork="true" failonerror="true">
                <classpath>
                    <pathelement location="${build.dir}/jarjar-${jarjar.version}.jar" />
                    <pathelement location="build/asm-9.1.jar" />
                    <pathelement location="build/asm-commons-9.1.jar" />
                </classpath>
                <arg value="process" />
                <arg value="jarjar.rules" />
                <arg value="@{input}" />
                <arg value="@{output}" />
            </java>
        </sequential>
    </macrodef>

    <target name="java-driver-core.shade" depends="jarjar.get,java-driver-core.get">
        <mkdir dir="${build.dir}/lib/jars" />
        <jarjar input="${build.dir}/shaded/java-driver-core-shaded-${base.java4DriverVersion}.jar"
            output="${build.dir}/lib/jars/java-driver-core-shaded-${base.java4DriverVersion}.jar" />
        <jarjar input="${build.dir}/shaded/java-driver-guava-shaded-${base.java4DriverVersion}.jar"
            output="${build.dir}/lib/jars/java-driver-guava-shaded-${base.java4DriverVersion}.jar" />
        <jarjar input="${build.dir}/shaded/native-protocol-${base.java4NativeProtocolVersion}.jar"
            output="${build.dir}/lib/jars/native-protocol-${base.java4NativeProtocolVersion}.jar" />
    </target>

    <target name="scylla-driver-core.override.install" if="scylla-driver-core.override.want"
        depends="init" description="Fetch Scylla Driver Core from Maven Local Repository">
        <echo>Use local Scylla Driver Core library ${lib.override.com.scylladb.scylla-driver-core}</echo>
        <copy file="${lib.override.com.scylladb.scylla-driver-core}"
            tofile="${scylla-driver-core.build.path}" />
        <copy file="${lib.override.com.scylladb.scylla-driver-core}"
            tofile="${scylla-driver-core.repo-cache.path}" />
        <touch file="${scylla-driver-core.override.done.flag.path}" />
    </target>

    <target name="scylla-driver-core.override.cleanup"
        unless="scylla-driver-core.override.want, scylla-driver-core.override.done"
        depends="init" description="Remove Scylla Driver Core from Maven From Local Repository">
        <delete quiet="true" failonerror="false" file="${scylla-driver-core.build.path}" />
        <delete quiet="true" failonerror="false" file="${scylla-driver-core.repo-cache.path}/" />
        <delete quiet="true" failonerror="false"
            file="${scylla-driver-core.override.done.flag.path}" />
    </target>

    <target name="scylla-driver-core.override"
        depends="init,scylla-driver-core.override.install,scylla-driver-core.override.cleanup" />

    <target name="build" depends="resolver-retrieve-build,build-project"
        description="Compile cassandra-stress classes" />

    <target name="build_java">
        <javac fork="true"
            compiler="modern"
            debug="true"
            debuglevel="${debuglevel}"
            encoding="utf-8"
            destdir="${build.classes.main}"
            includeantruntime="false"
            release="${release.version}"
            memorymaximumsize="512M">
            <src path="${build.src.java}" />
            <compilerarg value="-proc:none" />
            <classpath>
                <path refid="cassandra-stress.classpath" />
            </classpath>
        </javac>
    </target>

    <target depends="init" name="build-project">
        <echo message="${ant.project.name}: ${ant.file}" />
        <antcall target="build_java" />
        <copy todir="${build.classes.main}">
            <fileset dir="${build.src.resources}" />
        </copy>
    </target>

    <target name="jar" depends="build" description="Assemble the cassandra-stress JAR file">
        <mkdir dir="${build.dir}/lib/" />
        <jar destfile="${build.dir}/lib/cassandra-stress.jar">
            <fileset dir="${build.classes.main}" />
            <manifest>
                <attribute name="Implementation-Version" value="${version}" />
            </manifest>
        </jar>
    </target>

    <target name="artifacts" depends="jar"
        description="Create cassandra-stress release artifacts">
        <mkdir dir="${dist.dir}" />
        <fixcrlf srcdir="conf" includes="**/*" eol="lf" eof="remove" />
        <fixcrlf srcdir="bin" includes="**/*" eol="lf" eof="remove" />
        <copy todir="${dist.dir}/lib">
            <fileset dir="${build.dir.lib}/jars" />
            <fileset dir="${build.dir.lib}">
                <include name="cassandra-stress.jar" />
            </fileset>
        </copy>

        <copy todir="${dist.dir}/conf">
            <fileset dir="conf" />
        </copy>

        <copy todir="${dist.dir}/bin">
            <fileset dir="bin" />
        </copy>

        <copy todir="${dist.dir}/">
            <fileset dir="${basedir}">
                <include name="*.txt" />
            </fileset>
        </copy>

        <copy todir="${dist.dir}/examples/">
            <fileset dir="${basedir}/examples/">
                <include name="*.yaml" />
            </fileset>
        </copy>

        <tar compression="gzip" longfile="gnu"
            destfile="${build.dir}/cassandra-stress-bin.tar.gz">
            <tarfileset dir="${dist.dir}" prefix="cassandra-stress">
                <include name="**" />
                <exclude name="bin/*" />
            </tarfileset>
            <tarfileset dir="${dist.dir}" prefix="cassandra-stress" mode="755">
                <include name="bin/*" />
                <exclude name="bin/*.in.sh" />
            </tarfileset>
        </tar>

        <tar compression="gzip" longfile="gnu"
            destfile="${build.dir}/cassandra-stress-src.tar.gz">
            <tarfileset dir="${basedir}"
                prefix="cassandra-stress-src">
                <include name="**" />
                <exclude name="build/**" />
                <exclude name="lib/**" />
                <exclude name=".git/**" />
                <exclude name="venv/**" />
                <exclude name="bin/*" />
                <exclude name="**/__pycache__/**" />
                <exclude name=".project" />
                <exclude name=".classpath" />
                <exclude name=".settings/**" />
                <exclude name=".externalToolBuilders/**" />
                <exclude name="ide/nbproject/private/**" />
                <exclude name="Dockerfile" />
                <exclude name=".dockerignore" />
                <exclude name=".claude/**" />
                <exclude name="CLAUDE.md" />
                <exclude name="tasks/**" />
                <exclude name="docs/standards/**" />
                <exclude name="docs/INDEX.md" />
            </tarfileset>
            <tarfileset dir="${basedir}" prefix="cassandra-stress-src" mode="755">
                <include name="tools/bin/*" />
            </tarfileset>
        </tar>

        <checksum forceOverwrite="yes" todir="${build.dir}" fileext=".sha256" algorithm="SHA-256">
            <fileset dir="${build.dir}">
                <include name="cassandra-stress-bin.tar.gz" />
                <include name="cassandra-stress-src.tar.gz" />
            </fileset>
        </checksum>
        <checksum forceOverwrite="yes" todir="${build.dir}" fileext=".sha512" algorithm="SHA-512">
            <fileset dir="${build.dir}">
                <include name="cassandra-stress-bin.tar.gz" />
                <include name="cassandra-stress-src.tar.gz" />
            </fileset>
        </checksum>
    </target>

    <target name="build-test" depends="build"
        description="Compile test classes" unless="no-build-test">
        <javac
            compiler="modern"
            debug="true"
            debuglevel="${debuglevel}"
            destdir="${test.classes}"
            includeantruntime="true"
            release="${release.version}"
            encoding="utf-8">
            <compilerarg value="-proc:none" />
            <classpath>
                <path refid="cassandra-stress.classpath.test" />
                <path refid="cassandra-stress.classpath" />
            </classpath>
            <src path="${test.unit.src}" />
        </javac>
        <copy todir="${test.classes}">
            <fileset dir="${test.resources}" />
        </copy>
    </target>

    <target name="test" depends="build-test" description="Run the unit tests, or one class with -Dtest.name=ClassNameTest">
        <mkdir dir="${build.test.dir}/output" />
        <junit fork="on" forkmode="once" failureproperty="testfailed"
            maxmemory="1024m" timeout="${test.timeout}">
            <formatter type="xml" usefile="true" />
            <formatter type="brief" usefile="false" />
            <jvmarg value="-ea" />
            <jvmarg value="-Djava.io.tmpdir=${tmp.dir}" />
            <classpath>
                <path refid="cassandra-stress.classpath" />
                <path refid="cassandra-stress.classpath.test" />
                <pathelement location="${test.classes}" />
            </classpath>
            <batchtest todir="${build.test.dir}/output">
                <fileset dir="${test.unit.src}" includes="**/${test.name}.java" />
            </batchtest>
        </junit>
        <fail message="Some test(s) failed." if="testfailed" />
    </target>
</project>
